export {
  isMetaAdsConfigured,
  parseAccounts,
  queryOverview,
  queryCampaigns,
  queryAdsets,
  queryAds,
  queryTimeseries,
  queryBreakdown,
  type MetaAdsAccount,
  type MetaAdsMetrics,
  type MetaAdsAction,
  type MetaAdsCampaignEntry,
  type MetaAdsAdsetEntry,
  type MetaAdsAdEntry,
  type MetaAdsTimeseriesEntry,
  type MetaAdsBreakdownEntry,
} from "./client";
